# Generated by Django 3.1.2 on 2021-03-01 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='theloai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentheloai', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='baiviet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenbaiviet', models.CharField(max_length=200)),
                ('noidung', models.TextField()),
                ('ngay', models.DateTimeField(auto_now_add=True)),
                ('hinh', models.ImageField(null=True, upload_to='')),
                ('matheloai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.theloai')),
            ],
        ),
    ]
